// GENERATED by sync-ai-presets.mjs from contracts/ai-presets.json (schema 1) — DO NOT EDIT.
// Canonical file: dev/contracts/ai-presets.json; regenerate with the sync script, never hand-edit.

export const AI_PRESETS_SCHEMA = 1;

export const PROVIDER_PRESET_ORDER = [
  "openai",
  "gemini",
  "openrouter",
  "anthropic",
  "groq",
  "mistral",
  "deepseek",
  "ollama",
] as const;

export interface ProviderPresetData {
  label: string;
  wireType: 'openai_compatible' | 'anthropic' | 'google';
  apiBase: string;
  fixedBase: boolean;
  local: boolean;
  keyUrl?: string;
  preferredModel?: { modelId: string; name: string; caps: string[] };
  curatedModels?: string[];
  sttModel?: string;
  steps?: string[];
  freeTierNote?: string;
}

export const PROVIDER_PRESET_DATA: Record<string, ProviderPresetData> = {
    openai: {
      label: "OpenAI",
      wireType: "openai_compatible",
      apiBase: "https://api.openai.com/v1",
      fixedBase: false,
      local: false,
      keyUrl: "https://platform.openai.com/api-keys",
      preferredModel: { modelId: "gpt-5.6-terra", name: "GPT-5.6 Terra", caps: ["text", "tools", "vision"] },
      curatedModels: ["gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.6-sol", "whisper-1"],
      sttModel: "whisper-1",
      steps: ["Open {url} and sign in.", "Create a new secret key.", "Copy the key — it starts with sk-. Note: DeepSeek keys look similar.", "Paste it below and connect."],
    },
    gemini: {
      label: "Google Gemini",
      wireType: "google",
      apiBase: "https://generativelanguage.googleapis.com/v1beta",
      fixedBase: true,
      local: false,
      keyUrl: "https://aistudio.google.com/app/apikey",
      preferredModel: { modelId: "gemini-3.8-flash", name: "Gemini 3.8 Flash", caps: ["text", "tools", "vision"] },
      curatedModels: ["gemini-3.8-flash"],
      steps: ["Open {url} and sign in with a Google account.", "Create an API key — the free tier is enough to start.", "Copy the key — it starts with AIza.", "Paste it below and connect."],
      freeTierNote: "Google offers a free AI Studio tier — no credit card required.",
    },
    openrouter: {
      label: "OpenRouter",
      wireType: "openai_compatible",
      apiBase: "https://openrouter.ai/api/v1",
      fixedBase: false,
      local: false,
      keyUrl: "https://openrouter.ai/settings/keys",
      preferredModel: { modelId: "openrouter/auto", name: "Auto (best match)", caps: ["text", "tools"] },
      curatedModels: ["openrouter/auto"],
      steps: ["Open {url} and sign in.", "Create an API key.", "Copy the key — it starts with sk-or-v1-.", "Paste it below and connect."],
      freeTierNote: "OpenRouter lists free models alongside paid ones.",
    },
    anthropic: {
      label: "Anthropic",
      wireType: "anthropic",
      apiBase: "https://api.anthropic.com",
      fixedBase: true,
      local: false,
      keyUrl: "https://console.anthropic.com/settings/keys",
      preferredModel: { modelId: "claude-sonnet-5", name: "Claude Sonnet 5", caps: ["text", "tools", "vision"] },
      curatedModels: ["claude-sonnet-5"],
      steps: ["Open {url} and sign in.", "Create an API key.", "Copy the key — it starts with sk-ant-.", "Paste it below and connect."],
    },
    groq: {
      label: "Groq",
      wireType: "openai_compatible",
      apiBase: "https://api.groq.com/openai/v1",
      fixedBase: false,
      local: false,
      keyUrl: "https://console.groq.com/keys",
      steps: ["Open {url} and sign in.", "Create an API key.", "Copy the key — it starts with gsk_.", "Paste it below and connect."],
    },
    mistral: {
      label: "Mistral",
      wireType: "openai_compatible",
      apiBase: "https://api.mistral.ai/v1",
      fixedBase: false,
      local: false,
      keyUrl: "https://console.mistral.ai/api-keys",
      steps: ["Open {url} and sign in.", "Create an API key.", "Copy the key and keep it private.", "Paste it below and connect."],
    },
    deepseek: {
      label: "DeepSeek",
      wireType: "openai_compatible",
      apiBase: "https://api.deepseek.com/v1",
      fixedBase: false,
      local: false,
      keyUrl: "https://platform.deepseek.com/api_keys",
      steps: ["Open {url} and sign in.", "Create an API key.", "Copy the key — it starts with sk-. Note: OpenAI keys look similar.", "Paste it below and connect."],
    },
    ollama: {
      label: "Ollama (local)",
      wireType: "openai_compatible",
      apiBase: "http://localhost:11434/v1",
      fixedBase: false,
      local: true,
      steps: ["Install Ollama from ollama.com.", "Pull a model, e.g. run: ollama pull llama3.3", "Make sure Ollama is running on this machine.", "Connect below — no API key needed."],
    },
};

export const KEY_PREFIX_HINT_DATA: { prefix: string; presetKey: string }[] = [
  { prefix: "sk-ant-", presetKey: "anthropic" },
  { prefix: "sk-or-v1-", presetKey: "openrouter" },
  { prefix: "gsk_", presetKey: "groq" },
  { prefix: "AIza", presetKey: "gemini" },
  { prefix: "sk-", presetKey: "openai" },
];
