// =============================================================================
// TEXT CONSTANTS — single home for user-facing strings (main + renderer).
// Route every new user-visible string through this module so i18n adoption
// stays mechanical.
// =============================================================================

export const TEXT = {
  // =============================================================================
  // SYSTEM TRAY (main process)
  // =============================================================================
  TRAY_TOOLTIP: 'Desktop Assistant',
  TRAY_SHOW: 'Show',
  TRAY_HIDE: 'Hide',
  TRAY_SETTINGS: 'Settings',
  TRAY_DESKTOP: 'Open desktop mode',
  TRAY_ABOUT: 'About',
  TRAY_QUIT: 'Quit',

  // =============================================================================
  // SHARED BUTTONS
  // =============================================================================
  CANCEL_BUTTON: 'Cancel',
  SAVE_BUTTON: 'Save',
  DELETE_BUTTON: 'Delete',
  CLEAR_BUTTON: 'Clear',
  EDIT_BUTTON: 'Edit',
  CLOSE_BUTTON: 'Close',
  COPY_BUTTON: 'Copy',
  REMOVE_BUTTON: 'Remove',

  // =============================================================================
  // LAUNCHER (ChatApp)
  // =============================================================================
  LAUNCHER_ROLE_LABEL: 'Assistant',
  LAUNCHER_CONVERSATION_TITLE: 'Conversation',
  LAUNCHER_EMPTY_STATE: 'Ask AI anything…',
  LAUNCHER_NEW_BUTTON: '+ New',
  LAUNCHER_TOGGLE_HISTORY: 'Toggle history',
  LAUNCHER_TOGGLE_HISTORY_COLLAPSE: '⟨',
  LAUNCHER_TOGGLE_HISTORY_EXPAND: '⟩',
  LAUNCHER_HISTORY_SHOW: 'Show conversations',
  LAUNCHER_HISTORY_HIDE: 'Hide conversations',
  LAUNCHER_SETTINGS_TITLE: 'Settings',
  LAUNCHER_MORE_BUTTON: 'More',
  LAUNCHER_OPEN_DESKTOP: 'Open desktop mode (Ctrl+D)',
  LAUNCHER_TURN_FAILED: 'The turn failed.',
  LAUNCHER_DISMISS_ERROR: 'Dismiss error',

  CONFIRM_CLEAR_TITLE: 'Clear conversation',
  CONFIRM_CLEAR_DESCRIPTION: 'Remove all messages in this conversation?',
  CONFIRM_DELETE_TITLE: 'Delete conversation',
  CONFIRM_DELETE_DESCRIPTION: 'This conversation will be removed permanently.',

  // =============================================================================
  // DESKTOP WINDOW (DesktopApp)
  // =============================================================================
  DESKTOP_APP_TITLE: 'Desktop Assistant',
  DESKTOP_NEW_CHAT: 'New chat',
  DESKTOP_FLOW_TITLE: 'Working on it…',
  DESKTOP_SHOW_INSPECTOR: 'Show inspector',
  DESKTOP_HIDE_INSPECTOR: 'Hide inspector',
  DESKTOP_MINIMIZE: 'Minimize',
  DESKTOP_HIDE_TO_TRAY: 'Hide to tray',
  DESKTOP_DROP_FILES: 'Drop files to attach',
  DESKTOP_EXPORT_DIALOG_TITLE: 'Export conversation',
  DESKTOP_EXPORT_FALLBACK_TITLE: 'conversation',
  EXPORT_FORMAT_MARKDOWN: 'Markdown',
  EXPORT_FORMAT_JSON: 'JSON',

  // =============================================================================
  // COMPOSER
  // =============================================================================
  COMPOSER_PLACEHOLDER: 'Ask AI anything — / for commands',
  COMPOSER_ATTACH_FILES: 'Attach files',
  COMPOSER_SHARE_SCREEN: 'Share screen',
  COMPOSER_SELECT_FROM_FILES: 'Select from files',
  COMPOSER_VOICE_INPUT: 'Voice input',
  COMPOSER_STOP_RECORDING: 'Stop recording',
  COMPOSER_STOP_STREAM: 'Stop generating',
  COMPOSER_REMOVE_ATTACHMENT: 'Remove attachment {index}',
  COMPOSER_ATTACHMENT_SUMMARY: '{count} attached',
  ATTACHMENT_IMAGE: 'Image',
  ATTACHMENT_SCREEN_CAPTURE: 'Screen capture',

  // =============================================================================
  // SCREEN PICKER
  // =============================================================================
  PICKER_DIALOG_LABEL: 'Select a screen or window',
  PICKER_TITLE: 'Select a Screen or Window',
  PICKER_NO_PREVIEW: 'no preview',
  PICKER_NO_SOURCES: 'No sources available.',

  // =============================================================================
  // LAUNCHER MENU
  // =============================================================================
  MENU_LAUNCHER_LABEL: 'Launcher menu',
  MENU_NEW_CONVERSATION: 'New conversation',
  MENU_EXPAND: 'Expand (Ctrl+E)',
  LAUNCHER_COMPACT_MODE: 'Launcher mode (Ctrl+E)',
  MENU_SETTINGS: 'Settings',

  // =============================================================================
  // NOTICES
  // =============================================================================
  NOTICE_DISMISS: 'Dismiss notification',

  // =============================================================================
  // TRACE STRIP
  // =============================================================================
  TRACE_STEP: 'step',
  TRACE_STEPS: 'steps',
  TRACE_RESUMED: 'resumed',
  TRACE_RUNNING: '…',
  TRANSCRIPT_SCROLL_LATEST: 'Scroll to latest',

  // =============================================================================
  // APPROVALS
  // =============================================================================
  APPROVAL_GROUP_LABEL: 'Tool approval',
  APPROVAL_TITLE: 'Approval needed',
  APPROVAL_READ_BADGE: 'read',
  APPROVAL_RISK_STATE_CHANGING: 'Changes things',
  APPROVAL_RISK_DESTRUCTIVE: 'Destructive',
  APPROVAL_CONFIRM_EVERY_TIME: 'confirmed every time',
  APPROVAL_DESTRUCTIVE_HINT: 'Destructive tools are confirmed for every single call',
  APPROVAL_AUTO_DENY_HINT: 'Auto-denied when the countdown ends',
  APPROVAL_AUTO_DENY_IN: 'auto-deny in {seconds}s',
  APPROVAL_MORE_COUNT: '(+{count} more)',
  APPROVAL_DENY: 'Deny',
  APPROVAL_ALLOW_ONCE: 'Allow once',
  APPROVAL_THIS_SESSION: 'This session',
  APPROVAL_ALWAYS: 'Always',
  APPROVAL_DENIED_MESSAGE: 'Denied by the user.',
  APPROVAL_EDIT_ARGS: 'Edit args',
  APPROVAL_ARGS_LABEL: 'Arguments for {toolName}',
  APPROVAL_INVALID_JSON: 'Invalid JSON.',
  APPROVAL_EDIT_NOTICE: 'Edited args run instead of the original request.',

  // =============================================================================
  // DOWNLOADS
  // =============================================================================
  DOWNLOAD_GROUP_LABEL: 'File download',
  DOWNLOAD_TITLE: 'Downloading',
  DOWNLOAD_CANCEL: 'Cancel download',
  DOWNLOAD_CANCELLED: 'Cancelled',
  DOWNLOAD_SAVING: 'Finishing…',
  DOWNLOAD_PERCENT: '{percent}%',
  DOWNLOAD_BYTES: '{loaded} of {total}',
  DOWNLOAD_UNKNOWN_SIZE: '{loaded} downloaded',
  DOWNLOAD_SPEED: '{speed}/s',

  // =============================================================================
  // FILE ARTIFACTS
  // =============================================================================
  ARTIFACT_GROUP_LABEL: 'Files from this turn',
  ARTIFACT_OPEN: 'Open {name}',
  ARTIFACT_REVEAL: 'Show {name} in folder',
  ARTIFACT_FOLDER_BADGE: 'folder',
  ARTIFACT_OPEN_FAILED: 'Could not open: {error}',

  // =============================================================================
  // AUTOMATION (schedules)
  // =============================================================================
  AUTOMATION_NAV: 'Automation',
  AUTOMATION_NAV_DESCRIPTION: 'Scheduled prompts',
  AUTOMATION_TITLE: 'Scheduled prompts',
  AUTOMATION_DESCRIPTION:
    'Prompts that run on a schedule in their own conversation. Only you can create or edit them — the assistant cannot.',
  AUTOMATION_EMPTY: 'No schedules yet. Create one to have a prompt run on a rhythm.',
  AUTOMATION_EMPTY_CTA: 'New schedule',
  AUTOMATION_LOADING: 'Loading schedules…',
  AUTOMATION_LOAD_ERROR: 'Schedules could not be loaded.',
  AUTOMATION_RETRY: 'Retry',
  AUTOMATION_NEW: 'New schedule',
  AUTOMATION_EDIT: 'Edit schedule',
  AUTOMATION_RUN_NOW: 'Run now',
  AUTOMATION_RUNNING: 'Running…',
  AUTOMATION_ENABLED: 'Enabled',
  AUTOMATION_NEXT_RUN: 'Next run {when}',
  AUTOMATION_NEVER_RUN: 'not run yet',
  AUTOMATION_LAST_RUN: 'Last run: {outcome}',
  AUTOMATION_DELETE: 'Delete schedule',
  AUTOMATION_DELETE_CONFIRM_TITLE: 'Delete schedule?',
  AUTOMATION_DELETE_CONFIRM_BODY: '“{name}” will stop running. This cannot be undone.',
  AUTOMATION_WIZARD_NAME: 'Name',
  AUTOMATION_WIZARD_NAME_PLACEHOLDER: 'Morning briefing',
  AUTOMATION_WIZARD_PROMPT: 'Prompt',
  AUTOMATION_WIZARD_PROMPT_PLACEHOLDER: 'What should the assistant do each time this fires?',
  AUTOMATION_WIZARD_RHYTHM: 'Rhythm',
  AUTOMATION_WIZARD_RHYTHM_INTERVAL: 'Every N minutes',
  AUTOMATION_WIZARD_RHYTHM_DAILY: 'Daily at',
  AUTOMATION_WIZARD_RHYTHM_WEEKDAYS: 'Weekdays at',
  AUTOMATION_WIZARD_RHYTHM_CRON: 'Advanced cron',
  AUTOMATION_WIZARD_MINUTES: 'Minutes',
  AUTOMATION_WIZARD_TIME: 'Time',
  AUTOMATION_WIZARD_CRON_HINT: '5-field cron: minute hour day month weekday — evaluated in the selected timezone.',
  AUTOMATION_WIZARD_TIMEZONE: 'Timezone',
  AUTOMATION_WIZARD_SAVE: 'Save schedule',
  AUTOMATION_WIZARD_CANCEL: 'Cancel',
  AUTOMATION_WIZARD_INVALID: 'Please check the highlighted fields.',
  AUTOMATION_SAVED: 'Schedule saved.',
  AUTOMATION_DELETED: 'Schedule deleted.',
  AUTOMATION_RUN_QUEUED: 'Queued — it runs after the current turn.',
  AUTOMATION_RELATIVE_NOW: 'in less than a minute',
  AUTOMATION_RELATIVE_MINUTES: 'in {count} min',
  AUTOMATION_RELATIVE_HOURS: 'in {hours} h {minutes} min',
  AUTOMATION_RELATIVE_DAYS: 'in {days} d {hours} h',

  // =============================================================================
  // DOCS INDEX (local RAG)
  // =============================================================================
  DOCS_INDEX_TITLE: 'Document index',
  DOCS_INDEX_HINT:
    'Index a folder so docs_search can find passages in its markdown, text and PDF files. Indexing is local-only.',
  DOCS_INDEX_BUSY: 'Indexing…',
  DOCS_INDEX_COUNTS: '{files} files · {chunks} passages',
  DOCS_REINDEX: 'Re-index',

  // =============================================================================
  // TTS / SPEECH (plan 12 §6)
  // =============================================================================
  SPEECH_PREPARING: 'Preparing audio…',
  SPEECH_SPEAKING: 'Speaking…',
  SPEECH_STOP: 'Stop speaking',
  SPEECH_FAILED: 'Speech failed: {error}',
  SPEECH_SPEAK_REPLY: 'Speak reply',
  SPEECH_SPEAK_SELECTION: 'Speak selection',
  VOICE_SPEAK_REPLIES: 'Speak replies',
  VOICE_SPEAK_REPLIES_HINT:
    'Read finished replies aloud via the tts task model (OpenAI-compatible speech endpoint, or native Gemini TTS). Off by default.',
  VOICE_SPEAK_VOICE: 'Voice',
  VOICE_SPEAK_SPEED: 'Speed',

  // =============================================================================
  // TOOL USAGE (plan 12 §7)
  // =============================================================================
  USAGE_TITLE: 'Usage',
  USAGE_WINDOW: 'Stats window',
  USAGE_REFRESH: 'Refresh usage',
  USAGE_HINT: 'Tool activity from the local audit log (arguments are hashed, never stored).',
  USAGE_LOADING: 'Loading usage…',
  USAGE_ERROR: 'Usage stats could not be loaded.',
  USAGE_EMPTY: 'No tool activity in this window yet.',
  USAGE_TOTAL: '{count} audited calls',
  USAGE_FAILURES: 'Recent failures',
  USAGE_BAR_LABEL: '{tool}: {count} calls',
  USAGE_OK: '{count} ok',
  USAGE_ERRORS: '{count} errors',
  USAGE_DENIED: '{count} denied',
  USAGE_AVG: 'avg {ms} ms',
  APPS_USAGE_TITLE: 'App usage',
  APPS_USAGE_HINT: 'Audited tool calls attributed per app (same local audit log).',
  APPS_USAGE_EMPTY: 'No app tool activity in this window yet.',
  APPS_USAGE_BAR_LABEL: '{app}: {count} calls',

  // =============================================================================
  // PERSONA (plan 12 §7)
  // =============================================================================
  INSPECTOR_PERSONA: 'Persona',
  INSPECTOR_PERSONA_PLACEHOLDER: 'e.g. You are a terse senior reviewer…',
  INSPECTOR_PERSONA_HINT:
    'Applies to this conversation only, on top of the provider system prompt. The launcher keeps the global prompt.',

  // =============================================================================
  // INSPECTOR
  // =============================================================================
  INSPECTOR_TURN: 'Turn',
  INSPECTOR_TRACE: 'Trace',
  INSPECTOR_ATTACHMENTS: 'Attachments',
  INSPECTOR_MODEL: 'Model',
  INSPECTOR_EXPORT: 'Export',
  INSPECTOR_TOOLS: 'Tools',
  INSPECTOR_OUTCOME_IDLE: 'idle',
  INSPECTOR_NEXT_TURN: 'Next turn: {model}',
  INSPECTOR_NO_STEPS: 'No trace steps yet.',
  INSPECTOR_NO_ATTACHMENTS: 'None on the last message.',
  INSPECTOR_COPY_STEP: 'Copy step detail',
  INSPECTOR_CLEAR_MODEL_LABEL: 'Use default model',
  INSPECTOR_MODEL_LABEL: 'Model for this conversation',
  INSPECTOR_MODEL_HINT: 'Override for this conversation; empty = the default model.',

  // =============================================================================
  // SLASH COMMANDS
  // =============================================================================
  SLASH_SCREENSHOT_NO_ARGS: '/screenshot takes no arguments.',
  SLASH_SHELL_USAGE: 'Usage: /shell <command>',
  SLASH_OPEN_USAGE: 'Usage: /open <url | path | app>',
  SLASH_UNKNOWN_COMMAND: "Unknown command '/{command}'. Available: /screenshot, /shell, /open.",
  SLASH_HINT_SCREENSHOT: 'Capture the screen',
  SLASH_HINT_SHELL: 'Run: {command}',
  SLASH_HINT_OPEN: 'Open {target}',
  SLASH_HINT_LAUNCH: 'Launch {app}',

  // =============================================================================
  // COMMANDS (plan 14)
  // =============================================================================
  COMMAND_NEW_CONVERSATION: 'New conversation',
  COMMAND_NEW_CONVERSATION_SUBTITLE: 'Start a fresh chat',
  COMMAND_TOGGLE_EXPAND: 'Expand or collapse',
  COMMAND_TOGGLE_EXPAND_SUBTITLE: 'Switch launcher size',
  COMMAND_OPEN_DESKTOP: 'Open desktop mode',
  COMMAND_OPEN_DESKTOP_SUBTITLE: 'Full-window assistant with transcript',
  COMMAND_OPEN_SETTINGS: 'Open settings',
  COMMAND_OPEN_SETTINGS_SUBTITLE: 'Configure providers, tools and commands',
  COMMAND_HIDE: 'Hide assistant',
  COMMAND_HIDE_SUBTITLE: 'Send the launcher to the tray',
  COMMAND_QUIT: 'Quit Desktop Assistant',
  COMMAND_QUIT_SUBTITLE: 'Exit the application',
  COMMAND_CALCULATOR: 'Calculator',
  COMMAND_CALCULATOR_SUBTITLE: 'Evaluate a math expression',
  COMMAND_CALCULATOR_KEYWORDS: 'math compute',
  COMMAND_CALC_USAGE: 'Usage: /calc <expression>',
  COMMAND_CALC_ERROR: 'Calculation failed: {error}',
  COMMAND_CALC_RESULT: '= {value}',
  COMMAND_FILE_SEARCH: 'Search files',
  COMMAND_FILE_SEARCH_SUBTITLE: 'Find files in granted folders by name pattern',
  COMMAND_FILE_SEARCH_KEYWORDS: 'find files locate',
  COMMAND_FILES_USAGE: 'Usage: /files <pattern>',
  COMMAND_FILES_NO_ROOTS: 'No folders granted yet. Grant a folder in Settings → Tools to search files.',
  COMMAND_RESEARCH: 'Research topic',
  COMMAND_RESEARCH_SUBTITLE: 'Multi-step web research with sources',
  COMMAND_RESEARCH_KEYWORDS: 'research deep dive web sources',
  COMMAND_RESEARCH_USAGE: 'Usage: /research <topic>',
  COMMAND_TOOL_TURN: 'Runs through the chat turn path (same approvals as the assistant).',
  COMMAND_TURN_IN_PROGRESS: 'A turn is already running. Wait for it to finish, then try again.',
  COMMAND_EXECUTE_FAILED: 'Command failed: {error}',
  COMMAND_PALETTE_LABEL: 'Commands',
  COMMAND_PALETTE_EMPTY: 'No matching commands.',
  COMMAND_GROUP_PINNED: 'Pinned',
  COMMAND_GROUP_RECENT: 'Recent',
  COMMAND_GROUP_SUGGESTED: 'Suggested',
  COMMAND_GROUP_RESULTS: 'Results',
  COMMAND_CATEGORY_APPS: 'Applications',
  COMMAND_CATEGORY_TOOLS: 'Tools',
  COMMAND_CATEGORY_WEB: 'Web',
  COMMAND_CATEGORY_NAVIGATION: 'Navigation',
  COMMAND_CATEGORY_CUSTOM: 'Custom',
  COMMAND_CATEGORY_INTEGRATIONS: 'Integrations',
  COMMAND_UNKNOWN: "Unknown command '/{command}'.",
  COMMAND_ARG_USAGE: 'Usage: /{alias} {args}',
  COMMAND_COPY_DONE: 'Result copied',
  COMMAND_OPEN_USAGE: 'Usage: /open <url | path | app>',
  COMMAND_APP_SUBTITLE: 'Application',
  COMMAND_WEB_BROWSER_FALLBACK: 'No search provider configured — opened the search in your browser.',
  COMMAND_WEB_BROWSER_MODE: 'Opened the search in your browser.',
  COMMAND_WEB_USAGE: 'Usage: /web <query>',
  TRANSLATE_USAGE: 'Usage: /tr [language] <text> — e.g. /tr el Good morning',
  TRANSLATE_RESULT_META: 'via {engine} · {route}',
  COMMAND_MINI_TRANSLATE_TITLE: 'Translate',
  COMMAND_MINI_TRANSLATE_HINT: 'Live translation — Enter copies · Esc exits',
  COMMAND_MINI_TRANSLATE_PLACEHOLDER: 'Type text to translate…',
  TRANSLATION_MINI_PENDING: 'Translating…',
  TRANSLATION_MINI_ERROR: 'Translation failed: {error}',
  COMMAND_PIN: 'Pin',
  COMMAND_UNPIN: 'Unpin',
  COMMAND_CONFIGURE: 'Configure',
  COMMAND_DISABLE: 'Disable',
  COMMAND_OPEN_APP: 'Open',
  COMMAND_MINI_CALC_TITLE: 'Calculator',
  COMMAND_MINI_CALC_PLACEHOLDER: 'Type an expression — Enter copies the result',
  COMMAND_MINI_HINT: 'Enter copies the result · Esc or /exit exits',
  COMMAND_MINI_EXIT: 'Exit mini app',
  COMMAND_MINI_GROUP: 'Mode',
  COMMAND_MINI_EXIT_TITLE: 'Exit {app}',
  COMMAND_COPY_RESULT: 'Copy result',
  COMMAND_MINI_BLOCKED: "'/{command}' isn't available while {app} is open — exit the mini app first.",

  // =============================================================================
  // SETTINGS — COMMANDS TAB (plan 14 §6)
  // =============================================================================
  SETTINGS_NAV_COMMANDS: 'Commands',
  SETTINGS_NAV_COMMANDS_DESCRIPTION: 'Palette, apps, integrations, history',
  COMMANDS_PALETTE_TITLE: 'Command palette',
  COMMANDS_ENABLED_LABEL: 'Enable the command palette',
  COMMANDS_LIST_TITLE: 'All commands',
  COMMANDS_LIST_SEARCH: 'Search commands',
  COMMANDS_DETAIL_TITLE: 'Command details',
  COMMANDS_DETAIL_ALIASES: 'Extra aliases',
  COMMANDS_DETAIL_DEFAULTS: 'Argument defaults',
  COMMANDS_DETAIL_AGENT: 'Allow the assistant to invoke this',
  COMMANDS_DETAIL_PIN: 'Pin to top',
  COMMANDS_DETAIL_HIDDEN: 'Hide this command',
  COMMANDS_DETAIL_TEST: 'Test run',
  COMMANDS_DETAIL_TEST_OK: 'Result: {text}',
  COMMANDS_AGENT_WARNING: '{count} commands are agent-invocable — very large tool catalogs can degrade model tool selection.',
  COMMANDS_APPS_TITLE: 'Applications',
  COMMANDS_APPS_LAUNCH: 'Allow app launching',
  COMMANDS_APPS_DISCOVERY: 'Discover installed apps',
  COMMANDS_APPS_RESCAN: 'Rescan apps',
  COMMANDS_APPS_COUNT: '{count} apps found',
  COMMANDS_APPS_HIDDEN: 'Hidden apps',
  COMMANDS_APPS_RESTORE: 'Restore',
  COMMANDS_WEB_TITLE: 'Web search',
  COMMANDS_WEB_INLINE: 'Inline results',
  COMMANDS_WEB_BROWSER: 'Open in browser',
  COMMANDS_HISTORY_TITLE: 'History',
  COMMANDS_HISTORY_ENABLED: 'Remember command usage',
  COMMANDS_HISTORY_RETENTION: 'Keep history for {days} days',
  COMMANDS_HISTORY_CLEAR: 'Clear history',
  COMMANDS_HISTORY_RECENT: 'Recent commands',
  COMMANDS_INTEGRATIONS_TITLE: 'Integrations',
  COMMANDS_INTEGRATIONS_IMPORT: 'Import pack',
  COMMANDS_INTEGRATIONS_EMPTY: 'No integrations installed.',
  COMMANDS_INTEGRATIONS_JSON: 'Paste integration.json',
  COMMANDS_INTEGRATIONS_SECRETS: 'Secret values',
  COMMANDS_INTEGRATIONS_COMMANDS: '{count} commands',
  COMMANDS_CUSTOM_TITLE: 'My commands',
  COMMANDS_CUSTOM_NEW: 'New command',
  COMMANDS_CUSTOM_NAME: 'Name',
  COMMANDS_CUSTOM_KIND: 'Kind',
  COMMANDS_CUSTOM_KIND_TOOL: 'Tool command',
  COMMANDS_CUSTOM_KIND_PROMPT: 'Prompt',
  COMMANDS_CUSTOM_TOOL: 'Tool',
  COMMANDS_CUSTOM_PROMPT: 'Prompt text',
  COMMANDS_CUSTOM_ALIASES: 'Aliases',
  COMMANDS_ALIASES_ADD: 'Add alias',
  COMMANDS_ALIASES_REMOVE: 'Remove alias',
  COMMANDS_INSTANCES: 'Instances',
  COMMANDS_INSTANCES_HINT: 'Bound copies of this command with their own arguments and alias.',
  COMMANDS_INSTANCES_ADD: 'New instance',
  COMMANDS_CUSTOM_ARGS: 'Argument templates',
  COMMANDS_CUSTOM_ARGS_HINT: 'Use {{1}}, {{2}}… for palette arguments',
  COMMANDS_CONFIGURE_HINT: 'Right-click a row in the palette to pin, configure or disable it.',

  // =============================================================================
  // SESSION (useChatSession)
  // =============================================================================
  SESSION_NO_MODEL: 'No default chat model is configured. Pick one in Settings → API Settings.',
  SESSION_TURN_ERROR: 'Error: {error}',
  TURN_LIMIT_STEP: 'I hit my step budget before gathering enough to answer this. Try a narrower question.',
  TURN_LIMIT_TOKEN: 'This investigation grew too large for one turn. Try smaller, focused questions.',
  TURN_LIMIT_TIME: 'I ran out of time mid-investigation. Here is what I found so far.',
  NOTICE_TURN_LIMIT_STEP: 'Partial answer — the step budget was reached before the investigation completed.',
  NOTICE_TURN_LIMIT_TOKEN: 'Partial answer — the turn grew too large to complete the investigation.',
  NOTICE_TURN_LIMIT_TIME: 'Partial answer — time ran out before the investigation completed.',
  HISTORY_TRIMMED_LABEL: 'Older context trimmed',
  HISTORY_TRIMMED_SUMMARY: '{count} older messages dropped to fit the model context window',
  APP_SELECTION_LABEL: 'App selection',
  APP_SELECTION_SUMMARY: 'Using {bound}{droppedSuffix}',
  APP_SELECTION_DROPPED_SUFFIX: ' · {dropped} app(s) not matched',
  APP_SELECTION_NONE: 'No app tools matched this request',
  APPS_SELECTION_UNAVAILABLE: '{names}: tools could not be loaded — the server may be unreachable',
  APPS_VIEW_APPS: 'Apps',
  APPS_VIEW_SETTINGS: 'Settings',
  APPS_ADD_APP: 'Add app',
  APPS_ADD_MODE_PRESET: 'From preset',
  APPS_ADD_MODE_CUSTOM: 'Custom MCP server',
  APPS_CARD_TOOLS: '{count} tools',
  APPS_MASTER_SWITCH_TITLE: 'All apps enabled',
  APPS_MASTER_SWITCH_HINT: 'Master switch: disabled apps never bind to the agent or the palette.',
  APPS_MATCHING_HELP_TITLE: 'How app matching works',
  APPS_SCOPE_SAVE: 'Save rules',
  APPS_SCOPE_TAB: 'Scope',
  APPS_CUSTOM_HINT: 'Connect any MCP-compatible server. Tools load on the first connection; tune them in Details.',
  APPS_NAV_MATCHING_HELP: 'App matching compares English keywords in your message against tool tags, tool names and the app name. Mention an app by name to use it.',
  APPS_EMPTY: 'No tool apps yet — add one from a preset below.',
  APPS_SOURCE_MCP: 'MCP',
  APPS_SOURCE_NATIVE: 'Native group',
  APPS_HEALTH_HEALTHY: 'Healthy',
  APPS_HEALTH_UNAVAILABLE: 'Unavailable',
  APPS_HEALTH_ERROR: 'Error',
  APPS_HEALTH_DISABLED: 'Disabled',
  APPS_FILTER_ALL: 'All',
  APPS_SEARCH_PLACEHOLDER: 'Search apps',
  APPS_ENABLED_LABEL: '{name} enabled',
  APPS_REMOVE: 'Remove',
  APPS_DETAILS: 'Details',
  APPS_REMOVE_CONFIRM_TITLE: 'Remove {name}?',
  APPS_REMOVE_CONFIRM_DESCRIPTION: 'The app, its backing server config and its stored secrets (keyring entries) are all removed. This cannot be undone.',
  APPS_REMOVE_CONFIRM_ACTION: 'Remove app',
  APPS_DETAIL_TITLE: '{name} details',
  APPS_CONNECTION_TITLE: 'Connection',
  APPS_ENDPOINT_LABEL: 'Server endpoint',
  APPS_TOKEN_LABEL: 'Access token (stored in the OS keyring)',
  APPS_TOKEN_SET: 'A token is stored in the keyring.',
  APPS_SECRETS_KEYS: 'Stored secret names: {keys}',
  APPS_TEST_ROW: 'Test connection',
  APPS_TEST_ACTION: 'Test',
  APPS_TEST_OK: 'Connected · {latency} ms · {count} tools',
  APPS_TEST_FAIL: 'Connection failed: {error}',
  APPS_TOOLS_TITLE: 'Tools',
  APPS_TOOLS_AUTOSAVE: 'Changes apply immediately — no save needed.',
  APPS_TOOLS_EMPTY: 'No tools listed yet — run Test or send a message to load them.',
  APPS_TOOLS_SEARCH_PLACEHOLDER: 'Filter tools',
  APPS_TOOLS_FILTER_EMPTY: 'No tools match the filter.',
  APPS_TOOLS_GROUP_LABEL: '{group} ({count})',
  APPS_ICON_PICKER_LABEL: 'App icon',
  APPS_ICON_PICKER_CLEAR: 'Default',
  APPS_DIRECTIVES_TITLE: 'Standing directives',
  APPS_DIRECTIVES_HINT: 'Always injected while this app is enabled. Example: "For all Home Assistant tools use the app tools — never shell commands."',
  APPS_DIRECTIVES_LABEL: 'Directives',
  APPS_DIRECTIVES_SAVE: 'Save directives',
  APPS_TOOL_NEW_BADGE: 'new',
  APPS_TOOL_RISK_LABEL: '{name} risk override',
  APPS_TOOL_TAGS_LABEL: '{name} keyword tags',
  APPS_TOOL_ENABLED_LABEL: '{name} enabled',
  APPS_TOOL_UNDO: '{name} disabled — ',
  APPS_UNDO: 'Undo',
  APPS_SCOPE_TITLE: 'Device scope (entity allow/deny rules)',
  APPS_SCOPE_HINT: 'Ordered rules, last match wins. Patterns are globs over entity ids: light.*, lock.*, *.',
  APPS_SCOPE_ADD: 'Add rule',
  APPS_SCOPE_ALLOW: 'Allow',
  APPS_SCOPE_DENY: 'Deny',
  APPS_SCOPE_EFFECT_LABEL: 'Effect',
  APPS_SCOPE_PATTERN_LABEL: 'Pattern',
  APPS_SCOPE_PREVIEW: 'Preview against discovered devices',
  APPS_SCOPE_PREVIEW_ACTION: 'Refresh preview',
  APPS_SCOPE_PREVIEW_ALLOWED: 'allowed',
  APPS_SCOPE_PREVIEW_BLOCKED: 'blocked',
  APPS_SCOPE_PREVIEW_EMPTY: 'No devices discovered yet — connect and list devices first.',
  APPS_EXPOSURE_TITLE: 'Exposure',
  APPS_EXPOSURE_ALWAYS: 'Always available',
  APPS_EXPOSURE_RELEVANCE: 'When relevant to the message',
  APPS_EXPOSURE_DEFERRED: 'Deferred behind provider tool search',
  APPS_EXPOSURE_DEFERRED_REASON: 'Deferred needs a model with server-side tool search (Claude Sonnet 4+/Opus 4+/Haiku 4.5+ or gpt-5.4+ on OpenAI).',
  APPS_CUSTOM_ADD: 'Add custom app',
  APPS_CUSTOM_TITLE: 'Add custom MCP app',
  APPS_CUSTOM_NAME: 'App name',
  APPS_CUSTOM_TYPE: 'Connection type',
  APPS_CUSTOM_URL: 'Server URL',
  APPS_CUSTOM_COMMAND: 'Command',
  APPS_CUSTOM_ARGS: 'Arguments (space-separated)',
  APPS_CUSTOM_TOKEN: 'Bearer token (optional — stored in the OS keyring)',
  APPS_CUSTOM_SAVE: 'Add app',
  APPS_ADVANCED_TITLE: 'Advanced server options',
  APPS_CUSTOM_ENV: 'Environment (JSON object of strings)',
  APPS_CUSTOM_HEADERS: 'Headers (JSON object of strings)',
  APPS_CUSTOM_ALLOWLIST: 'Tool allowlist (comma-separated, empty = all tools)',
  APPS_CUSTOM_TIMEOUT: 'Tool timeout (ms)',
  APPS_CUSTOM_MAXCONC: 'Max concurrent calls',
  APPS_CUSTOM_JSON_ERROR: '{field}: {error}',
  APPS_CUSTOM_NUMBER_ERROR: '{field}: must be a positive whole number',
  APPS_CONNECTION_SAVE: 'Save connection',
  APPS_PRESETS_TITLE: 'Presets',
  APPS_PRESETS_DESCRIPTION: 'Bundled, reviewed integration presets.',
  APPS_PRESET_ADD: 'Add {name}',
  APPS_PRESET_PREVIEW_TITLE: 'Add {name}',
  APPS_PRESET_PREVIEW_RISKS: 'Permissions this app will request:',
  APPS_PRESET_PREVIEW_NOTES: 'Usage guidance shipped with this preset (applied while the app is active):',
  APPS_PRESET_ENDPOINT_LABEL: 'Home Assistant URL',
  APPS_PRESET_TOKEN_LABEL: 'Long-lived access token',
  APPS_PRESET_SAVE: 'Add app',
  APPS_BUDGET_TITLE: 'Tool budget',
  APPS_BUDGET_DESCRIPTION: 'Warn above this total number of agent tools across all apps.',
  APPS_BUDGET_LABEL: 'Budget',
  APPS_BUDGET_BOUND: '{count} tools currently bound (native + apps)',
  APPS_BUDGET_OVER: 'Over budget — apps will be dropped per the exposure order until the toolset fits.',
  SESSION_DELETED: 'Deleted!',
  SESSION_PDF_FAILED: 'Failed to read PDF: {error}',
  SESSION_VOICE_FAILED: 'Voice input failed: {error}',
  VOICE_LISTENING: 'Listening…',
  VOICE_TRANSCRIBING: 'Transcribing…',

  // =============================================================================
  // SETTINGS WINDOW
  // =============================================================================
  SETTINGS_WINDOW_TITLE: 'Settings',
  SETTINGS_WINDOW_LOADING: 'Loading settings…',
  SETTINGS_VERSION_UNAVAILABLE: 'N/A',
  SETTINGS_NAV_GENERAL: 'General',
  SETTINGS_NAV_GENERAL_DESCRIPTION: 'Theme and startup behavior',
  SETTINGS_NAV_API: 'API Settings',
  SETTINGS_NAV_API_DESCRIPTION: 'Providers, models and task assignments',
  SETTINGS_NAV_VOICE: 'Voice',
  SETTINGS_NAV_VOICE_DESCRIPTION: 'Speech input and spoken replies',
  SETTINGS_NAV_TOOLS: 'Tools',
  SETTINGS_NAV_TOOLS_DESCRIPTION: 'Native tools, folders and MCP servers',
  SETTINGS_NAV_APPS: 'Apps (AI tools)',
  SETTINGS_NAV_APPS_DESCRIPTION: 'Tool apps, presets and device scope',
  SETTINGS_NAV_HOTKEYS: 'Hotkeys',
  SETTINGS_NAV_HOTKEYS_DESCRIPTION: 'Global keyboard shortcuts',
  SETTINGS_RESET_DEFAULTS: 'Reset Defaults',
  SETTINGS_EXPORT_CONFIG: 'Export Config',
  SETTINGS_IMPORT_CONFIG: 'Import Config',
  SETTINGS_SAVE_CHANGES: 'Save Changes',
  SETTINGS_SAVED: 'Saved',
  SETTINGS_SAVED_OK: 'Settings saved successfully!',
  SETTINGS_RESET_TITLE: 'Reset to Default Settings',
  SETTINGS_RESET_DESCRIPTION: 'Are you sure you want to reset all settings to their default values? This action cannot be undone.',
  SETTINGS_RESET_CONFIRM: 'Yes, Reset',
  SETTINGS_IMPORT_TITLE: 'Confirm Settings Import',
  SETTINGS_IMPORT_DESCRIPTION: 'This will overwrite your current settings with the imported file. Continue?',
  SETTINGS_IMPORT_CONFIRM: 'Import & Overwrite',
  SETTINGS_LOAD_FAILED: 'Failed to load settings: {error}',
  SETTINGS_SAVE_FAILED: 'Failed to save settings: {error}',
  SETTINGS_RESET_OK: 'Settings have been reset to defaults.',
  SETTINGS_RESET_FAILED: 'Failed to reset settings: {error}',
  SETTINGS_EXPORT_OK: 'Settings successfully exported to {path}',
  SETTINGS_EXPORT_FAILED: 'Failed to export settings: {error}',
  SETTINGS_EXPORT_DIALOG_TITLE: 'Export Settings',
  SETTINGS_IMPORT_INVALID_JSON: 'Invalid JSON file. Could not parse the settings file.',
  SETTINGS_IMPORT_INCOMPATIBLE: 'Invalid configuration file. The file is not compatible.',
  SETTINGS_IMPORT_FAILED: 'Import failed: {error}',
  SETTINGS_IMPORT_OK: 'Settings imported and saved successfully.',

  // =============================================================================
  // SETTINGS — GENERAL TAB
  // =============================================================================
  GENERAL_TITLE: 'General Settings',
  GENERAL_SUBTITLE: 'Configure general application behavior.',
  GENERAL_THEME: 'Theme',
  GENERAL_AUTOSTART: 'Launch Desktop Assistant on system startup',
  GENERAL_AUTOSTART_HINT: 'Starts hidden in the tray on Windows and Linux; on macOS the window opens at login.',
  GENERAL_AUTOSTART_DEV_HINT: 'Unavailable while running a development build — enable it from an installed app.',
  GENERAL_OPEN_ON_SUMMON: 'Open on summon',
  GENERAL_MODE_LAUNCHER: 'Launcher window',
  GENERAL_MODE_DESKTOP: 'Desktop window',
  GENERAL_MODE_HINT: 'Which window the global summon hotkey opens.',
  GENERAL_AUTO_EXPAND: 'Auto-expand the launcher when a response overflows',
  GENERAL_NOTIFY_COMPLETE: 'Notify when a turn finishes in the background',
  GENERAL_HIDE_ON_BLUR: 'Hide the launcher when it loses focus',
  GENERAL_HIDE_ON_BLUR_HINT: 'Skips native file dialogs so attaching files still works.',
  GENERAL_TRANSPARENT: 'Transparent window (glass corners)',
  GENERAL_TRANSPARENT_HINT: 'Applies immediately. On Cinnamon/Mint a transparent always-on-top window may fail to render — if the window disappears, untick this from the tray menu → Settings.',

  // =============================================================================
  // SETTINGS — API TAB
  // =============================================================================
  API_PROVIDERS_SECTION: 'Providers',
  API_PROVIDERS_HINT: 'Credentials for OpenAI-compatible endpoints. Keys live in the OS keyring, never in the config file.',
  API_CONNECTION: 'Connection',
  API_TEST: 'Test',
  API_TEST_OK: 'Reachable',
  API_TEST_FAIL: 'Unreachable',
  API_MODELS_COUNT: '{count} models',
  API_KEY_HINT: 'key {hint}',
  API_ADD_MODEL: 'Add model',
  API_ADD_ALL: 'Add all ({count})',
  API_MODEL_SEARCH: 'Search models…',
  API_MODEL_LIST_LABEL: 'Label',
  API_TEMPERATURE_LABEL: 'Temperature',
  API_MAX_TOKENS_LABEL: 'Max tokens',
  API_MODELS_TITLE: 'Models',
  API_MODELS_SUBTITLE: 'Register models per provider — pull the remote catalog or add entries manually. Capabilities gate task assignments.',
  API_TASKS_TITLE: 'Task Assignments',
  API_TASKS_SUBTITLE: 'Choose which model serves each AI task. The chat model also answers for unassigned tasks.',
  API_TASK_CHAT: 'Chat turns',
  API_TASK_CHAT_DESCRIPTION: 'The model that answers in the launcher and desktop windows.',
  API_TASK_TITLES: 'Conversation titles',
  API_TASK_TITLES_DESCRIPTION: 'Generates a title after the first exchange; without it the opening message is used.',
  API_TASK_STT: 'Transcription (voice input)',
  API_TASK_STT_DESCRIPTION: 'Audio-capable model that turns dictation into text. Voice input is off until one is assigned.',
  API_TASK_VOICE_ENDPOINT: 'Voice post-processing',
  API_TASK_VOICE_ENDPOINT_DESCRIPTION: 'One small-model call per phrase: judges completeness and optionally returns cleaned text. Powers auto-send and transcript fixes.',
  API_TASK_TTS: 'Speech (TTS)',
  API_TASK_TTS_DESCRIPTION: 'Reads finished replies aloud via an OpenAI-compatible /audio/speech endpoint, or natively for Google Gemini TTS models. Assign a speech model (tts-1, kokoro, gemini-*-tts, …).',
  API_TASK_PLUMBING: 'Internal plumbing',
  API_TASK_PLUMBING_DESCRIPTION: 'Cheap helper model for internal calls (title-ish work, memory dedupe). Falls back to the chat model when unset.',
  API_TASK_INTENT: 'Decisions (intent)',
  API_TASK_INTENT_DESCRIPTION: 'Model the decision engine consults when it routes commands to tools (plan 20). Falls back to the chat model when unset.',
  API_TASK_TRANSLATE: 'Translation (LLM engine)',
  API_TASK_TRANSLATE_DESCRIPTION: 'Model used when the translation mode runs on the LLM (plan 19). Never falls back to the chat model — unassigned means the LLM engine is off.',
  VOICE_PAGE_TITLE: 'Voice',
  VOICE_PAGE_SUBTITLE: 'Speech input and spoken replies.',
  VOICE_ASSIGNED_TITLE: 'Assigned models',
  VOICE_MODEL_UNASSIGNED: 'Not assigned',
  VOICE_CONFIGURE_MODELS: 'Configure models',
  VOICE_ENABLE: 'Enable voice input',
  VOICE_LANGUAGE: 'Transcription language',
  VOICE_LANGUAGE_AUTO: 'Auto-detect',
  VOICE_LANGUAGE_HINT: 'Pin a language when auto-detect wobbles on accents or noise.',
  VOICE_LIVE_TRANSCRIPT: 'Live interim transcript',
  VOICE_LIVE_HINT: 'Transcribes each phrase after a short pause while you keep talking.',
  VOICE_PHRASE_GAP: 'Phrase pause',
  VOICE_PHRASE_GAP_HINT: 'How much silence closes a phrase before it is transcribed.',
  VOICE_GAP_SECONDS: '{seconds} s',
  VOICE_MAX_SEGMENT: 'Send every',
  VOICE_MAX_SEGMENT_OFF: 'Off',
  VOICE_MAX_SEGMENT_HINT: 'Commits the transcript after this much continuous speech, even without a pause. Needed for auto-send on long dictations.',
  VOICE_GAIN: 'Mic gain',
  VOICE_GAIN_HINT: 'Boost the input level used by silence detection and the live bars. Raise it if phrases are never committed.',
  VOICE_GAIN_TIMES: '{gain}×',
  VOICE_AUTO_SEND: 'Auto-send completed phrases',
  VOICE_AUTO_SEND_HINT: 'Sends the dictation by itself when the Voice post-processing model judges a phrase complete. Requires assigning that model above.',
  VOICE_AUTO_FIX: 'Fix text',
  VOICE_AUTO_FIX_HINT: 'Punctuation, capitals, spelling and filler removal applied to the transcript by the Voice post-processing model.',
  VOICE_FORMATTING: 'Formatting',
  VOICE_FORMATTING_HINT: 'Paragraph breaks and light structure for long dictations.',
  VOICE_CUSTOM_PROMPT: 'Custom instructions',
  VOICE_CUSTOM_PROMPT_PLACEHOLDER: 'e.g. technical terms, preferred spelling, style…',
  VOICE_CUSTOM_PROMPT_HINT: 'Appended to the post-processing instructions.',
  VOICE_CANCEL: 'Cancel dictation',
  TRACE_TIMELINE_TOGGLE: 'Turn trace',
  TRACE_TIMELINE_TOOLS: 'tools',
  TRACE_TIMELINE_TOTAL: 'Total',
  TRACE_TIMELINE_TOKENS: 'tokens',
  TRACE_TIMELINE_REASONING: 'Reasoning',
  TRACE_TIMELINE_ARGUMENTS: 'Arguments',
  TRACE_TIMELINE_RESPONSE: 'Response',
  TRACE_TIMELINE_DETAILS: 'details',
  TRACE_PHASE_THINKING: 'Thinking',
  TRACE_PHASE_TOOL_RESULT: 'Tool result',
  TRACE_PHASE_STREAMING: 'Streaming',
  TOOL_RESULT_VIEW: 'View result',
  TOOL_RESULT_VIEW_SCREENSHOT: 'View screenshot',
  TOOL_RESULT_MISSING: 'This result is no longer in memory (recent turns only).',
  TOOL_RESULT_TITLE: 'Tool result',
  TOOL_RESULT_COPY: 'Copy text',
  TOOL_RESULT_COPIED: 'Copied',
  TOOL_RESULT_STATUS_OK: 'ok',
  TOOL_RESULT_STATUS_ERROR: 'failed',
  TOOL_RESULT_ZOOM_IN: 'Zoom in',
  TOOL_RESULT_ZOOM_OUT: 'Zoom out',
  TOOL_RESULT_ZOOM_RESET: 'Reset zoom',
  TOOL_RESULT_PREV_IMAGE: 'Previous image',
  TOOL_RESULT_NEXT_IMAGE: 'Next image',
  TOOL_RESULT_IMAGE_OF: 'Image {current} of {total}',
  GENERAL_TRACE_DETAILS: 'Show turn trace details',
  GENERAL_TRACE_DETAILS_HINT: 'Timelines with tool calls and durations under assistant replies (launcher, expanded and desktop).',
  GENERAL_MEMORY_CONTEXT: 'Let the assistant use memory',
  GENERAL_MEMORY_CONTEXT_HINT: 'Recalls relevant memories at turn start and lets the assistant save new ones. Memories stay in the local database and can be managed in Settings → Tools.',
  GENERAL_CLIPBOARD_WATCHER: 'Offer clipboard on summon',
  GENERAL_CLIPBOARD_WATCHER_HINT: 'When the launcher opens, offer a chip if the clipboard changed since last time. Nothing is read unless you click it.',
  GENERAL_SELECTION_CAPTURE: 'Show "insert selection" button',
  GENERAL_SELECTION_CAPTURE_HINT: 'Adds a button next to the microphone that inserts the text you selected in another app (X11 Linux only). Passive read on click — never injects keystrokes, never touches your clipboard.',

  // Composer
  COMPOSER_INSERT_SELECTION: 'Insert my selection',
  CONTEXT_CLIPBOARD: 'Ask about clipboard',
  CONTEXT_SELECTION_BUSY: 'Reading selection…',
  CONTEXT_NO_SELECTION: 'No selection was captured.',
  VOICE_ATTACH_CONTEXT: 'Attach recent context',
  VOICE_ATTACH_CONTEXT_HINT: 'Gives the post-processing model the last exchange so names and terms stay consistent. Slightly slower, negligible cost.',
  VOICE_CLEAR_PENDING: 'Clear pending text',
  API_CAP_TEXT: 'Text',
  API_CAP_VISION: 'Vision',
  API_CAP_TOOLS: 'Tools',
  API_CAP_AUDIO: 'Audio',
  API_CAP_EMBEDDINGS: 'Embeddings',
  API_CAPS_HINT: 'Capabilities decide which tasks a model can be assigned to.',
  API_REASONING_EFFORT: 'Reasoning effort',
  API_REMOTE_LOADING: 'Loading catalog…',
  API_REMOTE_EMPTY: 'No further models in the remote catalog.',
  API_REMOTE_RETRY: 'Retry',
  API_EXTERNAL_ID_REQUIRED: 'Model id is required.',
  API_MANUAL_ID: 'Enter id manually',
  API_SELECT_MODEL: 'Model',
  API_PROVIDERS_EMPTY: 'Add a provider to register models.',
  API_DEFAULT_MODEL_TITLE: 'Default Chat Model',
  API_DEFAULT_MODEL_SUBTITLE: 'Select the default model. This will also set the default provider.',
  API_DEFAULT_MODEL_LABEL: 'Default Model',
  API_DEFAULT_MODEL_UNSET: 'Not set',
  API_PROVIDERS_TITLE: 'Configured Providers',
  API_PROVIDERS_SUBTITLE: 'The default provider is marked with a star.',
  API_NO_PROVIDERS: 'No providers configured.',
  API_ADD_PROVIDER: 'Add New Provider',
  API_EDIT_PROVIDER: 'Edit Provider',
  API_NAME_LABEL: 'Connection Name',
  API_NAME_PLACEHOLDER: 'e.g., My OpenAI Key',
  API_TYPE_LABEL: 'Provider Type',
  API_STORED_KEY_LABEL: 'Stored ({hint}) — leave empty to keep',
  API_KEY_HELP: 'Stored in OS-protected storage (keyring) — never in config files.',
  API_MODEL_LIST: 'Model List',
  API_MODEL_LIST_HINT: 'Refresh to load available models from the API.',
  API_REFRESH_MODELS: 'Refresh Models',
  API_ADD_CUSTOM_MODEL: 'Add Custom Model',
  API_CUSTOM_MODEL_PROMPT: 'Custom model name:',
  API_SAVE_PROVIDER: 'Save Provider',
  API_DELETE_TITLE: 'Confirm Deletion',
  API_DELETE_DESCRIPTION: 'Are you sure you want to delete "{name}"?',
  API_NAME_REQUIRED: 'Provider name is required.',
  API_PROVIDER_DELETED: 'Provider deleted successfully.',
  API_MODELS_FAILED: 'Failed to fetch models: {error}',
  API_UNKNOWN_ERROR: 'Unknown error',

  // =============================================================================
  // SETTINGS — HOTKEYS TAB
  // =============================================================================
  HOTKEYS_TITLE: 'Hotkey Settings',
  HOTKEYS_SUBTITLE: 'Manage global keyboard shortcuts. Some shortcuts are fixed and cannot be changed.',
  HOTKEYS_EDITABLE: 'Editable Hotkeys',
  HOTKEYS_FIXED: 'Fixed Hotkeys',
  HOTKEYS_NOT_SET: 'Not Set',
  HOTKEYS_RECORD: 'Record',
  HOTKEYS_DIALOG_LABEL: 'Recording hotkey for {label}',
  HOTKEYS_DIALOG_TITLE: 'Recording Hotkey for "{label}"',
  HOTKEYS_DIALOG_HINT: 'Press the desired key combination. Press Escape to cancel.',
  HOTKEYS_PRESS_KEYS: 'Press keys...',
  HOTKEYS_CLEAR: 'Clear',
  HOTKEYS_CLEAR_BUTTON: 'Unbind',
  HOTKEYS_COMMANDS_TITLE: 'Command Hotkeys',
  HOTKEYS_COMMANDS_HINT:
    'Bind your custom commands (Settings → Commands) to spare key combinations — the command runs as a normal turn, approvals still apply.',
  HOTKEYS_TAKEN: '"{accelerator}" is already assigned to another hotkey.',

  // =============================================================================
  // SETTINGS — TOOLS TAB
  // =============================================================================
  TOOLS_TITLE: 'Tools',
  TOOLS_SUBTITLE: 'Control what the assistant may do: native tools, folder access, and MCP servers. State-changing tools ask before they run; destructive tools confirm every single time.',
  TOOLS_NATIVE: 'Native tools',
  TOOLS_ENABLE_ARIA: 'Enable {name}',
  TOOLS_FOLDERS: 'Granted folders',
  TOOLS_ADD_FOLDER: 'Add folder',
  TOOLS_FOLDERS_HINT: 'File and shell tools may only touch folders you grant here.',
  TOOLS_NO_FOLDERS: 'No folders granted yet.',
  TOOLS_REMOVE_FOLDER_ARIA: 'Remove folder {root}',
  TOOLS_MCP: 'MCP servers',
  TOOLS_ADD_SERVER: 'Add server',
  TOOLS_MCP_HINT: 'Model Context Protocol servers add tools from local commands or remote endpoints. Secrets (env values, headers) are stored in the OS keyring, never in the config file.',
  TOOLS_NO_SERVERS: 'No servers configured.',
  TOOLS_TEST_CONNECTION: 'Test connection',
  TOOLS_TEST_RESULT: '{count} tools · {latency}ms',
  TOOLS_TEST_FAILED: 'failed',
  TOOLS_DELETE_SERVER: 'Delete server',
  TOOLS_SERVER_TOOLS_COUNT: '{count} tools',
  TOOLS_SERVER_ENV: 'env: {keys}',
  TOOLS_SERVER_HEADERS: 'headers: {keys}',
  TOOLS_REMOVE_CONFIRM: 'Remove this server and its stored secrets?',
  TOOLS_NAME_LABEL: 'Name',
  TOOLS_NAME_ARIA: 'Server name',
  TOOLS_NAME_PLACEHOLDER: 'my-server',
  TOOLS_TRANSPORT: 'Transport',
  TOOLS_TRANSPORT_STDIO: 'stdio (local command)',
  TOOLS_TRANSPORT_HTTP: 'HTTP (streamable)',
  TOOLS_TRANSPORT_SSE: 'SSE',
  TOOLS_COMMAND: 'Command',
  TOOLS_COMMAND_PLACEHOLDER: '/usr/bin/my-mcp-server',
  TOOLS_ARGS: 'Arguments',
  TOOLS_ARGS_PLACEHOLDER: '--port 3000',
  TOOLS_URL: 'URL',
  TOOLS_URL_ARIA: 'Server URL',
  TOOLS_URL_PLACEHOLDER: 'https://example.com/mcp',
  TOOLS_ENV_LABEL: 'Environment (JSON)',
  TOOLS_ENV_LABEL_STORED: ' — empty keeps stored values',
  TOOLS_ENV_ARIA: 'Environment variables as JSON',
  TOOLS_ENV_PLACEHOLDER: '{ "API_KEY": "…" }',
  TOOLS_HEADERS_LABEL: 'Headers (JSON)',
  TOOLS_HEADERS_ARIA: 'HTTP headers as JSON',
  TOOLS_HEADERS_PLACEHOLDER: '{ "Authorization": "Bearer …" }',
  TOOLS_ALLOWLIST: 'Tool allowlist (comma-separated, empty = all)',
  TOOLS_TIMEOUT: 'Tool timeout (ms, default 30000)',
  TOOLS_NAME_REQUIRED: 'Name is required.',
  TOOLS_SAVE_SERVER: 'Save server',
  TOOLS_JSON_OBJECT_REQUIRED: '{label} must be a JSON object.',

  // Tools tab — catalog overview
  TOOLS_SEARCH_ARIA: 'Search tools',
  TOOLS_SEARCH_PLACEHOLDER: 'Search tools…',
  TOOLS_SEARCH_CLEAR: 'Clear search',
  TOOLS_FILTER_ALL: 'All',
  TOOLS_FILTER_READ_ONLY: 'Read-only',
  TOOLS_FILTER_STATE_CHANGING: 'State-changing',
  TOOLS_FILTER_DESTRUCTIVE: 'Destructive',
  TOOLS_RISK_FILTER_ARIA: 'Filter by risk class',
  TOOLS_NO_MATCHES: 'No tools match the current search or filters.',
  TOOLS_TOTAL_COUNT: '{count} tools',
  TOOLS_ENABLED_COUNT: '{count} enabled',
  TOOLS_DISABLED_COUNT: '{count} disabled',
  TOOLS_GRANTED_COUNT: '{count} auto-approved',
  TOOLS_OVERRIDES_COUNT: '{count} custom verification',
  TOOLS_STATUS_FILTER_ARIA: 'Filter by verification status',
  TOOLS_CARD_DETAILS: 'Details',
  TOOLS_CARD_DETAILS_ARIA: 'Open details for {name}',
  TOOLS_BADGE_EDITABLE_ARGS: 'editable args',
  TOOLS_BADGE_GRANTED: 'always allowed',
  TOOLS_BADGE_AUTO_RUN: 'auto-run',
  TOOLS_BADGE_CUSTOM: 'custom',
  TOOLS_WORD_RULE: 'rule',
  TOOLS_WORD_RULES: 'rules',
  TOOLS_DISABLED_BADGE: 'disabled',

  // Tools tab — categories
  TOOLS_CAT_ALL: 'All categories',
  TOOLS_CAT_FILES: 'Files',
  TOOLS_CAT_SYSTEM: 'System',
  TOOLS_CAT_DESKTOP: 'Desktop',
  TOOLS_CAT_NETWORK: 'Network',
  TOOLS_CAT_POWER: 'Power',
  TOOLS_CAT_INTEGRATIONS: 'Integrations',
  TOOLS_CAT_MEMORY: 'Memory',
  TOOLS_CATEGORY_FILTER_ARIA: 'Filter by category',

  // Memory recall marker (trace strip)
  MEMORY_RECALL_LABEL: 'Context',
  MEMORY_ONE: 'memory',
  MEMORY_MANY: 'memories',
  MEMORY_RECALLED: 'recalled',

  // Memories manager (Tools tab)
  MEMORIES_TITLE: 'Memories',
  MEMORIES_SUBTITLE: 'What the assistant remembers across conversations. Stored only in the local database.',
  MEMORIES_COUNT: '{count} {word} stored',
  MEMORIES_SEARCH_ARIA: 'Search memories',
  MEMORIES_SEARCH_PLACEHOLDER: 'Search memories…',
  MEMORIES_LIST_ARIA: 'Stored memories',
  MEMORIES_LOADING: 'Loading memories…',
  MEMORIES_ERROR: 'Could not load memories.',
  MEMORIES_RETRY: 'Retry',
  MEMORIES_EMPTY: 'No memories yet',
  MEMORIES_EMPTY_HINT: 'Say "remember that…" in a chat and the assistant will keep it here.',
  MEMORIES_NO_MATCHES: 'No memories match your search.',
  MEMORIES_DELETE_ARIA: 'Forget memory: {content}',
  MEMORIES_UNDO: 'Undo',
  MEMORIES_FORGOT: 'Memory forgotten.',
  MEMORIES_SOURCE_USER: 'you',
  MEMORIES_SOURCE_ASSISTANT: 'assistant',
  MEMORIES_FROM_CONVERSATION: 'from conversation',
  MEMORIES_SMART_MERGE: 'Smart merge',
  MEMORIES_SMART_MERGE_HINT:
    'Let the internal plumbing model arbitrate near-duplicates on save. Memory text is sent to the assigned provider; deterministic dedupe always stays active.',
  MEMORIES_CONSOLIDATE: 'Consolidate now',
  MEMORIES_CONSOLIDATING: 'Consolidating…',
  MEMORIES_CONSOLIDATE_STATUS: 'Checked {checked} pair(s): {merged} merged, {kept} kept separate.',
  MEMORIES_CONSOLIDATE_COOLDOWN: 'Consolidation ran recently — try again in a minute.',
  MEMORIES_CONSOLIDATE_ERROR: 'Consolidation failed.',
  MEMORIES_MERGED_FROM: 'merged from {count}',

  // Tools tab — class defaults & presets
  TOOLS_DEFAULTS_TITLE: 'Default verification',
  TOOLS_DEFAULTS_HINT: 'Applies to built-in tools of that risk class unless a tool has its own override below. MCP tools always keep their own settings.',
  TOOLS_DEFAULTS_READONLY: 'Read-only tools',
  TOOLS_DEFAULTS_STATE_CHANGING: 'State-changing tools',
  TOOLS_DEFAULTS_DESTRUCTIVE: 'Destructive tools',
  TOOLS_DEFAULTS_READONLY_OPTIONS_ARIA: 'Default verification for read-only tools',
  TOOLS_DEFAULTS_STATE_CHANGING_OPTIONS_ARIA: 'Default verification for state-changing tools',
  TOOLS_DEFAULTS_RUN_SILENTLY: 'Run silently',
  TOOLS_DEFAULTS_ASK: 'Ask before running',
  TOOLS_DEFAULTS_STANDARD: 'Ask unless approved',
  TOOLS_DEFAULTS_NEVER: 'Run silently',
  TOOLS_DEFAULTS_ALWAYS_ASK: 'Always ask',
  TOOLS_DEFAULTS_DESTRUCTIVE_LOCKED: 'Always confirm every call (locked)',
  TOOLS_PRESETS_LABEL: 'Presets',
  TOOLS_PRESET_CAUTIOUS: 'Cautious',
  TOOLS_PRESET_CAUTIOUS_HINT: 'Read-only runs silently; everything else asks until you approve it.',
  TOOLS_PRESET_TRUSTED: 'Trusted workspace',
  TOOLS_PRESET_TRUSTED_HINT: 'Harmless actions (volume, clipboard, lock…) run silently; risky and destructive actions ask.',
  TOOLS_PRESET_MANUAL: 'Fully manual',
  TOOLS_PRESET_MANUAL_HINT: 'Every tool call asks for confirmation, including read-only ones.',
  TOOLS_PRESET_APPLY_ARIA: 'Apply the {name} preset',
  TOOLS_PRESET_CUSTOM: 'Custom',
  TOOLS_PRESET_CUSTOM_HINT: 'The defaults below were changed by hand.',
  TOOLS_DEFAULTS_SAVED: 'Default verification saved.',

  // Tools tab — detail modal
  TOOLS_DETAIL_TITLE: 'Tool details',
  TOOLS_PARAM_HEADER_NAME: 'Parameter',
  TOOLS_PARAM_HEADER_TYPE: 'Type',
  TOOLS_PARAM_HEADER_DESCRIPTION: 'Description',
  TOOLS_UNSAVED_CHANGES: 'Unsaved changes',
  TOOLS_VERIFICATION_MODE_GROUP_ARIA: 'Verification mode for {name}',
  TOOLS_DETAIL_ABOUT: 'About this tool',
  TOOLS_DETAIL_PARAMETERS: 'Parameters',
  TOOLS_DETAIL_PARAMETERS_EMPTY: 'This tool takes no parameters.',
  TOOLS_PARAM_REQUIRED: 'required',
  TOOLS_PARAM_OPTIONAL: 'optional',
  TOOLS_PARAM_DEFAULT: 'default: {value}',
  TOOLS_PARAM_ALLOWED_VALUES: 'Allowed values: {values}',
  TOOLS_PARAM_NAME_ARIA: 'Parameter {name}',
  TOOLS_VERIFICATION_TITLE: 'Verification',
  TOOLS_VERIFICATION_HINT: 'Choose when the assistant must ask you before this tool runs.',
  TOOLS_VERIFICATION_STANDARD: 'Standard',
  TOOLS_VERIFICATION_STANDARD_HINT: 'Follows the class default for this tool (set under Default verification).',
  TOOLS_VERIFICATION_ALWAYS_ASK: 'Always ask',
  TOOLS_VERIFICATION_ALWAYS_ASK_HINT: 'Every single call asks for confirmation, even for read-only tools and approved tools.',
  TOOLS_VERIFICATION_CONDITIONS: 'Ask only when…',
  TOOLS_VERIFICATION_CONDITIONS_HINT: 'Runs silently unless a rule below matches the call arguments; a matching rule asks.',
  TOOLS_VERIFICATION_NEVER: 'Never ask',
  TOOLS_VERIFICATION_NEVER_HINT: 'Every call runs automatically without confirmation.',
  TOOLS_VERIFICATION_DESTRUCTIVE_LOCKED: 'Destructive tools always confirm every call — this cannot be changed.',
  TOOLS_CONDITION_ADD: 'Add rule',
  TOOLS_CONDITION_REMOVE_ARIA: 'Remove rule {index}',
  TOOLS_CONDITION_PARAM_ARIA: 'Rule {index} parameter',
  TOOLS_CONDITION_OPERATOR_ARIA: 'Rule {index} condition',
  TOOLS_CONDITION_VALUE_ARIA: 'Rule {index} value',
  TOOLS_CONDITION_MATCH_ANY: 'Ask when ANY rule matches:',
  TOOLS_CONDITION_PARAM_PLACEHOLDER: 'Select a parameter',
  TOOLS_GRANT_TITLE: 'Approval shortcut',
  TOOLS_GRANT_ALLOW: 'Always allow this tool',
  TOOLS_GRANT_ALLOW_HINT: "Skips the confirmation dialog for this tool (same as the 'always allow' button in chat).",
  TOOLS_GRANT_REVOKE: 'Revoke',
  TOOLS_GRANT_ACTIVE: 'Always allowed',
  TOOLS_ENABLE_TITLE: 'Available to the assistant',
  TOOLS_ENABLE_HINT: 'Disabled tools are never offered to the model.',
  TOOLS_RISK_RECLASSIFY: 'Risk class',
  TOOLS_RISK_RECLASSIFY_HINT: 'MCP tools default to state-changing (always asks). Re-classify only if you trust the server.',
  TOOLS_VERIFICATION_APPLY: 'Apply',
  TOOLS_VERIFICATION_SAVED: 'Verification settings saved.',
  TOOLS_VERIFICATION_SAVE_FAILED: 'Could not save verification settings: {error}',

  // Tools tab — MCP tools
  TOOLS_MCP_TOOLS_TITLE: 'Server tools',
  TOOLS_MCP_TOOLS_LOAD: 'Load tools',
  TOOLS_MCP_TOOLS_LOADING: 'Connecting…',
  TOOLS_MCP_TOOLS_LOAD_FAILED: 'Could not list tools: {error}',
  TOOLS_MCP_TOOLS_EMPTY: 'The server exposes no tools.',
  TOOLS_MCP_TOOL_CONFIGURE: 'Configure',
  TOOLS_MCP_TOOL_CONFIGURE_ARIA: 'Configure tool {name}',

  // Tools tab — web search providers
  SEARCH_TITLE: 'Web search',
  SEARCH_HINT: 'Ordered provider instances the web_search tool uses: the first one that answers wins, the rest are fallback. API keys are stored in the OS keyring, never in the config file.',
  SEARCH_ADD: 'Add provider',
  SEARCH_NO_PROVIDERS: 'No providers configured — web_search will report that it is unavailable.',
  SEARCH_ENABLE_ARIA: 'Enable {name}',
  SEARCH_DELETE_ARIA: 'Delete provider {name}',
  SEARCH_MOVE_UP_ARIA: 'Move {name} up',
  SEARCH_MOVE_DOWN_ARIA: 'Move {name} down',
  SEARCH_TEST_ARIA: 'Test provider {name}',
  SEARCH_TEST_OK: '{count} result(s) · {latency}ms',
  SEARCH_TEST_FAILED: 'failed',
  SEARCH_DELETE_CONFIRM: 'Delete this provider and its stored key?',
  SEARCH_NAME_LABEL: 'Name',
  SEARCH_NAME_ARIA: 'Provider name',
  SEARCH_NAME_PLACEHOLDER: 'My SearXNG',
  SEARCH_TYPE_LABEL: 'Provider type',
  SEARCH_BASE_URL_LABEL: 'Base URL',
  SEARCH_BASE_URL_HINT: 'The SearXNG instance URL, e.g. http://home-server:8080 — the JSON API must be enabled.',
  SEARCH_BASE_URL_ARIA: 'Provider base URL',
  SEARCH_BASE_URL_PLACEHOLDER: 'http://home-server:8080',
  SEARCH_CX_LABEL: 'Engine id (cx)',
  SEARCH_CX_ARIA: 'Google Programmable Search engine id',
  SEARCH_KEY_LABEL: 'API key',
  SEARCH_KEY_LABEL_STORED: ' — empty keeps the stored key',
  SEARCH_KEY_ARIA: 'Provider API key',
  SEARCH_KEY_CLEAR: 'Clear stored key',
  SEARCH_KEY_CLEAR_ARIA: 'Clear the stored API key',
  SEARCH_TIMEOUT_LABEL: 'Timeout (ms, 1000–30000)',
  SEARCH_TIMEOUT_ARIA: 'Request timeout in milliseconds',
  SEARCH_MAX_RESULTS_LABEL: 'Default result count (1–10)',
  SEARCH_MAX_RESULTS_ARIA: 'Default result count',
  SEARCH_SAVE: 'Save provider',
  SEARCH_NAME_REQUIRED: 'Name is required.',
  SEARCH_BASE_URL_REQUIRED: 'A base URL is required for SearXNG.',
  DECISION_TITLE: 'Decision engine',
  DECISION_HINT: 'Route short commands straight to tools without a full chat turn. Everything else — and any doubt — falls through to the normal chat answer.',
  DECISION_ENGINE_LABEL: 'Engine',
  DECISION_ENGINE_ARIA: 'Decision engine',
  DECISION_ENGINE_OFF: 'Off',
  DECISION_ENGINE_OFF_HINT: 'Standard behavior: every input goes to the chat turn.',
  DECISION_ENGINE_LLM: 'Chat model (structured)',
  DECISION_ENGINE_LLM_HINT: 'Uses the Decisions (intent) task model — falls back to the chat model — to pick tools for short commands.',
  DECISION_ENGINE_NEEDLE: 'Local Needle model',
  DECISION_ENGINE_NEEDLE_HINT: 'Runs the bundled Needle 3 model on this device (download below, works offline after). Fast and private; asks for confirmation when unsure.',
  DECISION_WEIGHTS_PRESENT: 'Model downloaded and verified',
  DECISION_WEIGHTS_MISSING: 'Model not downloaded yet',
  DECISION_DOWNLOAD: 'Download model',
  DECISION_DOWNLOAD_ARIA: 'Download the local Needle model (~34 MB)',
  DECISION_DOWNLOAD_INPROGRESS: 'Downloading… {percent}%',
  DECISION_DOWNLOAD_CANCEL: 'Cancel download',
  DECISION_DOWNLOAD_ERROR: 'Download failed: {error}',
  DECISION_TEST_TITLE: 'Try a command',
  DECISION_TEST_HINT: 'Runs the engine without executing anything — shows what it would pick.',
  DECISION_TEST_PLACEHOLDER: 'dim the living room to 30',
  DECISION_TEST_ARIA: 'Decision test input',
  DECISION_TEST_RUN: 'Run test',
  DECISION_TEST_RUNNING: 'Running…',
  DECISION_TEST_OFF: 'Pick an engine above to test it.',
  DECISION_TEST_CALLS: 'Would call: {tools}',
  DECISION_TEST_NO_CALLS: 'Would not call any tool (chat answers instead).',
  DECISION_TEST_BAND_ACT: 'run it',
  DECISION_TEST_BAND_CONFIRM: 'ask you first',
  DECISION_TEST_BAND_REFUSE: 'let chat answer',
  DECISION_TEST_RESULT: '{confidence}% confident · would {band}',
  DECISION_TRACE_LABEL: 'Decision · {engine}',
  DECISION_TEST_ERROR: 'Test failed: {error}',
  DECISION_ACT_THRESHOLD_LABEL: 'Act above',
  DECISION_CONFIRM_THRESHOLD_LABEL: 'Ask above',
  DECISION_THRESHOLDS_HINT: 'Confidence thresholds: above "act" runs the tool (policy still applies), between the two asks for approval, below lets chat answer.',
  DECISION_ENGINE_NAME_LLM: 'Chat model',
  DECISION_ENGINE_NAME_NEEDLE: 'Needle',
  TRANSLATION_TITLE: 'Translation',
  TRANSLATION_HINT: 'The /tr command and the translate tool use these engines: configured services first, then the LLM model when the mode allows it. API keys are stored in the OS keyring, never in the config file.',
  TRANSLATION_MODE_LABEL: 'Engine mode',
  TRANSLATION_MODE_AUTO: 'Auto — services first, then LLM',
  TRANSLATION_MODE_SERVICE: 'Translation services only',
  TRANSLATION_MODE_LLM: 'LLM model only',
  TRANSLATION_MODE_HINT: 'When nothing is configured, /tr reports exactly what is missing instead of guessing.',
  TRANSLATION_PAD_DEBOUNCE_LABEL: 'Auto-translate delay',
  TRANSLATION_PAD_DEBOUNCE_HINT: 'How long the translate pad waits after you stop typing before it sends a request. Longer delays mean fewer engine calls.',
  TRANSLATION_PAD_DEBOUNCE_ARIA: 'Auto-translate delay in milliseconds',
  TRANSLATION_DEFAULT_TARGET_LABEL: 'Default target language',
  TRANSLATION_DEFAULT_TARGET_NONE: 'None — required per command',
  TRANSLATION_DEFAULT_TARGET_HINT: 'Used when /tr is called without a language.',
  TRANSLATION_CUSTOM_TITLE: 'Custom languages',
  TRANSLATION_CUSTOM_HINT: 'Add your own codes for scripts or languages beyond the built-in list — they work as targets and sources just like built-in codes.',
  TRANSLATION_CUSTOM_CODE_LABEL: 'Code',
  TRANSLATION_CUSTOM_NAME_LABEL: 'Name',
  TRANSLATION_CUSTOM_NATIVE_LABEL: 'Native name (optional)',
  TRANSLATION_CUSTOM_ADD: 'Add language',
  TRANSLATION_CUSTOM_INVALID_CODE: 'Codes use 2-12 characters: a-z, 0-9 and dashes.',
  TRANSLATION_CUSTOM_COLLISION: "'{code}' is already a built-in language.",
  TRANSLATION_CUSTOM_DUPLICATE: "'{code}' is already in the list.",
  TRANSLATION_CUSTOM_NAME_REQUIRED: 'A display name is required.',
  TRANSLATION_CUSTOM_EMPTY: 'No custom languages — the built-in list applies.',
  TRANSLATION_CUSTOM_REMOVE_ARIA: 'Remove custom language {code}',
  TRANSLATION_ADD: 'Add service',
  TRANSLATION_NO_PROVIDERS: 'No services configured — only the LLM engine can answer (when assigned).',
  TRANSLATION_SAVE: 'Save provider',
  TRANSLATION_NAME_LABEL: 'Name',
  TRANSLATION_NAME_ARIA: 'Provider name',
  TRANSLATION_NAME_REQUIRED: 'Name is required.',
  TRANSLATION_TYPE_LABEL: 'Service type',
  TRANSLATION_API_BASE_LABEL: 'Server URL',
  TRANSLATION_API_BASE_ARIA: 'Server URL',
  TRANSLATION_API_BASE_HINT_LT: 'Your LibreTranslate server, e.g. https://libretranslate.example.com',
  TRANSLATION_API_BASE_REQUIRED: 'A server URL is required for LibreTranslate.',
  TRANSLATION_API_BASE_HINT_DEEPL: 'Optional endpoint override — free keys ending in ":fx" are routed automatically.',
  TRANSLATION_KEY_LABEL: 'API key',
  TRANSLATION_KEY_LABEL_STORED: ' (stored)',
  TRANSLATION_KEY_CLEAR: 'Clear',
  TRANSLATION_KEY_CLEAR_ARIA: 'Clear the stored API key',
  TRANSLATION_KEY_HINT: 'Key: {hint}',
  TRANSLATION_TIMEOUT_LABEL: 'Timeout (ms)',
  TRANSLATION_TIMEOUT_ARIA: 'Timeout in milliseconds',
  TRANSLATION_ENABLE_ARIA: 'Toggle {name}',
  TRANSLATION_ORDER_LABEL: '#{position}',
  TRANSLATION_MOVE_UP_ARIA: 'Move {name} up',
  TRANSLATION_MOVE_DOWN_ARIA: 'Move {name} down',
  TRANSLATION_TEST_ARIA: 'Test {name}',
  TRANSLATION_TEST_OK: ' OK ({translation}, {latency}ms)',
  TRANSLATION_TEST_FAILED: ' failed',
  TRANSLATION_DELETE_ARIA: 'Delete {name}',
  TRANSLATION_DELETE_CONFIRM: 'Remove this provider and its stored key?',
  TRANSLATION_MODE_ARIA: 'Translation engine mode',
  TRANSLATION_DEFAULT_TARGET_ARIA: 'Default target language',
  SEARCH_KEY_HINT: 'key stored ({hint})',
  SEARCH_ORDER_LABEL: 'priority {position}',

  // =============================================================================
  // TURN PHASES (launcherState)
  // =============================================================================
  PHASE_QUEUED: 'Queued',
  PHASE_THINKING: 'Thinking',
  PHASE_WORKING: 'Working',
  PHASE_STREAMING: 'Streaming'
} as const;

// =============================================================================
// TEXT UTILITIES
// =============================================================================

/**
 * Replace placeholders in text with values
 */
export function interpolate(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (match, key) => {
    return values[key]?.toString() || match;
  });
}

/**
 * Get pluralized text based on count
 */
export function pluralize(count: number, singular: string, plural?: string): string {
  if (count === 1) {
    return singular;
  }
  return plural || `${singular}s`;
}

// Default export
export default TEXT;
