export const ANIMATIONS = {
  WINDOW_RESIZE_DURATION: 300,
  BUTTON_HOVER_DURATION: 200,
  RECORDING_PULSE_DURATION: 1000
} as const;

export const KEYBOARD_SHORTCUTS = {
  TOGGLE_INPUT_MODE: 'Tab',
  TOGGLE_RECORDING: 'F2',
  OPEN_SETTINGS: 'F3',
  TOGGLE_CONVERSATION: 'F4'
} as const;