#!/usr/bin/env bash
# check-byok-contract — BYOK setup contract gate (family plan 17, Layer "Gate tooling").
# Master: dev/scripts/check-byok-contract.sh (vendored copies stay byte-identical;
# drift is caught by dev's verify-wiring.sh).
#
# Rules:
#   R1 preset data is generated (header) and matches contracts/ai-presets.json (sync --check)
#   R2 no 'audio' capability literals under src/ (vocabulary is stt/tts post-freeze)
#   R3 setup orchestration lives in the sanctioned AI layer
#   R4 the uniform contract-test matrix file exists and names the core cases
#   R5 setup options naming (camelCase in TS; snake_case in Python payloads)
#
# Usage: check-byok-contract.sh [--self]   (run from the repo root)
set -uo pipefail

MODE=""
for arg in "$@"; do
  case "$arg" in
    --self) MODE="self" ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAIL=0

note()  { echo "  - $1"; }
bad()   { echo "  ✗ $1" >&2; FAIL=1; }
good()  { echo "  ✓ $1"; }

echo "byok contract gate: $ROOT"

# R1 — generated data present + no drift against the canonical file.
if [ -f "contracts/ai-presets.json" ] && [ -f "scripts/sync-ai-presets.mjs" ]; then
  GENERATED_TS="$ROOT/src/shared/ai/providerPresets.generated.ts"
  if [ -f "$GENERATED_TS" ]; then
    if head -1 "$GENERATED_TS" | grep -q "GENERATED by sync-ai-presets"; then
      if node scripts/sync-ai-presets.mjs --check "$GENERATED_TS" >/dev/null 2>&1; then
        good "R1 generated preset data matches contracts/ai-presets.json"
      else
        bad "R1 drift: providerPresets.generated.ts does not match contracts/ai-presets.json (regenerate via the sync script)"
      fi
    else
      bad "R1 $GENERATED_TS lacks the GENERATED header — data must come from the sync script"
    fi
  else
    note "R1 skipped (no generated TS module yet — required once the repo ships the setup surface)"
  fi
else
  note "R1 skipped (canonical file + sync script not vendored yet)"
fi

# R2 — no 'audio' capability literals under src/ (AppConfig.ts hosts the sanctioned
# load-time legacy migration shim audio → [stt, tts]; it is exempt).
AUDIO_HITS="$(grep -rn "'audio'" "$ROOT/src" 2>/dev/null | grep -v "providerPresets.generated" | grep -v "src/shared/config/AppConfig.ts" || true)"
if [ -n "$AUDIO_HITS" ]; then
  bad "R2 legacy 'audio' capability literals found (vocabulary is stt/tts):"
  echo "$AUDIO_HITS" >&2
else
  good "R2 no 'audio' capability literals outside the migration shim"
fi

# R3 — setup orchestration imported only by the AI layer + IPC handlers
# (renderer reaches it through the typed bridge — that is the sanctioned path).
if [ -f "$ROOT/src/main/ai/providers/setup.ts" ]; then
  OUTSIDE="$(grep -rln "from '@main/ai/providers/setup'" "$ROOT/src" 2>/dev/null | grep -v "src/main/ipc-handlers.ts" || true)"
  if [ -n "$OUTSIDE" ]; then
    bad "R3 setup module imported outside the AI layer / IPC surface:"
    echo "$OUTSIDE" >&2
  else
    good "R3 setup orchestration lives in src/main/ai/providers/ (IPC surface only)"
  fi
else
  note "R3 skipped (no TS setup module — Python repos assert their app/ai/providers/ location)"
fi

# R4 — the uniform contract-test matrix is present and names core cases.
MATRIX="$ROOT/tests/ai-provider-setup.test.ts"
if [ -f "$MATRIX" ]; then
  MISSING=""
  for case in "appends the fetched catalog" "never clobbers" "adopt" "persists nothing" "local_not_running" "suspectedVendor"; do
    grep -q "$case" "$MATRIX" || MISSING="$MISSING '$case'"
  done
  if [ -n "$MISSING" ]; then
    bad "R4 contract-test matrix missing cases:$MISSING"
  else
    good "R4 contract-test matrix present (core cases named)"
  fi
else
  note "R4 skipped (no TS contract-test file — Python repos assert their equivalent)"
fi

# R5 — options naming per platform (camelCase in TS sources).
OPTS_FILE="$ROOT/src/main/ai/providers/setup.ts"
if [ -f "$OPTS_FILE" ]; then
  if grep -q "curatedIds" "$OPTS_FILE" && grep -q "bindChat" "$OPTS_FILE" && grep -q "bindVision" "$OPTS_FILE" && grep -q "bindStt" "$OPTS_FILE"; then
    good "R5 setup options use the contract names (curatedIds/bindChat/bindVision/bindStt)"
  else
    bad "R5 setup options deviate from the contract names (curatedIds/bindChat/bindVision/bindStt)"
  fi
else
  note "R5 skipped (no TS setup module)"
fi

if [ "$FAIL" -eq 0 ]; then
  echo "byok contract: OK"
else
  echo "byok contract: FAILURES above" >&2
fi
exit "$FAIL"
